In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
feed_data = pd.read_excel('feedback_data.xlsx')
feed_data.head()

,Department,Year,Course,"Whether the lectures were well prepared, organized and course material is well structured?",Was the Blackboard writing clear and organised?,Were any Audio-Visual Aids used?,Were the lectures delivered with emphasize on fundamental concepts and with illustrative examples?,Whether difficult topics were taught with adequate attention and ease?,Did the faculty provide you new knowledge and has command over the subject?,Was the instructor enthusiastic about teaching?,Was the teacher able to deliver lectures with good communication skills?,"Were you encouraged to ask Questions, to make lectures interactive and lively?","Did the course improve your understanding and concepts, principles in this field and motivated you to think and learn?",Whether the teacher was effective in preparing the students for exam?,Were the assignments and tests challenging? (with new and novel problem solving approach),Was the evaluation fair and impartial? and did it help you to improve?,Did teacher give additional technical/non technical inputs by referring to internal/additional books?,"Whether teacher was always accessible to the student for counseling, guidance and solving queries of classroom hours?"
0,Computer Science and Engineering,1,1,7,4,8,9,2,7,7,2,8,7,6,3,8,2,1
1,Computer Science and Engineering,1,1,2,1,7,10,10,3,3,9,5,6,1,5,7,4,4
2,Computer Science and Engineering,1,1,1,3,2,5,8,7,1,7,5,5,3,4,0,8,2
3,Computer Science and Engineering,1,1,9,0,2,4,8,9,3,8,0,4,5,2,1,9,5
4,Computer Science and Engineering,1,1,8,2,9,5,0,8,1,2,6,9,9,10,5,2,3

In [3]:
feed_data.columns

Index(['Department', 'Year', 'Course',
       'Whether the lectures were well prepared, organized and course material is well structured?',
       'Was the Blackboard writing clear and organised?',
       'Were any Audio-Visual Aids used?',
       'Were the lectures delivered with emphasize on fundamental concepts and with illustrative examples?',
       'Whether difficult topics were taught with adequate attention and ease?',
       'Did the faculty provide you new knowledge and has command over the subject?',
       'Was the instructor enthusiastic about teaching?',
       'Was the teacher able to deliver lectures with good communication skills?',
       'Were you encouraged to ask Questions, to make lectures interactive and lively?',
       'Did the course improve your understanding and concepts, principles in this field and motivated you to think and learn?',
       'Whether the teacher was effective in preparing the students for exam?',
       'Were the assignments and tests challenging? (with new and novel problem solving approach)',
       'Was the evaluation fair and impartial? and did it help you to improve?',
       'Did teacher give additional technical/non technical inputs by referring to internal/additional books?',
       'Whether teacher was always accessible to the student for counseling, guidance and solving queries of classroom hours?'],
      dtype='object')

In [4]:

parameters = ['dept','year','course','course_material','blackboard_systematic','audio_visual_used','lectures_with_examples','difficult_topics','faculty_command_subject','teacher_enthusiastic','communication_skills','lectures_interactive','improve_concepts','teacher_effective_preparation','level_of_ass_test','evaluation_fair','additional_info','teacher_accessible']

feed_data = pd.read_excel('feedback_data.xlsx',names=parameters)
feed_data.head()

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible
0,Computer Science and Engineering,1,1,7,4,8,9,2,7,7,2,8,7,6,3,8,2,1
1,Computer Science and Engineering,1,1,2,1,7,10,10,3,3,9,5,6,1,5,7,4,4
2,Computer Science and Engineering,1,1,1,3,2,5,8,7,1,7,5,5,3,4,0,8,2
3,Computer Science and Engineering,1,1,9,0,2,4,8,9,3,8,0,4,5,2,1,9,5
4,Computer Science and Engineering,1,1,8,2,9,5,0,8,1,2,6,9,9,10,5,2,3

In [5]:
feed_data.columns

Index(['dept', 'year', 'course', 'course_material', 'blackboard_systematic',
       'audio_visual_used', 'lectures_with_examples', 'difficult_topics',
       'faculty_command_subject', 'teacher_enthusiastic',
       'communication_skills', 'lectures_interactive', 'improve_concepts',
       'teacher_effective_preparation', 'level_of_ass_test', 'evaluation_fair',
       'additional_info', 'teacher_accessible'],
      dtype='object')

In [6]:
feed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14400 entries, 0 to 14399
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   dept                           14400 non-null  object
 1   year                           14400 non-null  int64
 2   course                         14400 non-null  int64
 3   course_material                14400 non-null  int64
 4   blackboard_systematic          14400 non-null  int64
 5   audio_visual_used              14400 non-null  int64
 6   lectures_with_examples         14400 non-null  int64
 7   difficult_topics               14400 non-null  int64
 8   faculty_command_subject        14400 non-null  int64
 9   teacher_enthusiastic           14400 non-null  int64
 10  communication_skills           14400 non-null  int64
 11  lectures_interactive           14400 non-null  int64
 12  improve_concepts               14400 non-null  int64
 13  teacher_effective_preparation  14400 non-null  int64
 14  level_of_ass_test              14400 non-null  int64
 15  evaluation_fair                14400 non-null  int64
 16  additional_info                14400 non-null  int64
 17  teacher_accessible             14400 non-null  int64
dtypes: int64(17), object(1)
memory usage: 2.0+ MB

In [7]:
feed_data.isna().sum()

dept                             0
year                             0
course                           0
course_material                  0
blackboard_systematic            0
audio_visual_used                0
lectures_with_examples           0
difficult_topics                 0
faculty_command_subject          0
teacher_enthusiastic             0
communication_skills             0
lectures_interactive             0
improve_concepts                 0
teacher_effective_preparation    0
level_of_ass_test                0
evaluation_fair                  0
additional_info                  0
teacher_accessible               0
dtype: int64

In [8]:
feed_data.describe()

,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible
count,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000,14400.000000
mean,2.500000,4.500000,4.994653,5.049792,5.011042,5.046875,5.048403,4.994375,5.021667,5.028194,5.004514,4.997083,4.965347,4.982847,4.974028,5.008889,4.988889
std,1.118073,2.291367,2.913630,2.936385,2.924131,2.895659,2.923181,2.917060,2.936597,2.915774,2.915252,2.904837,2.926795,2.911820,2.920816,2.910605,2.912052
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.750000,2.750000,2.000000,3.000000,2.000000,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,3.000000,2.000000
50%,2.500000,4.500000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
75%,3.250000,6.250000,7.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
max,4.000000,8.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [9]:
feed_data.dept.unique()

array(['Computer Science and Engineering', 'Information Technology',
       'Electronic and Telecommunication Engineering',
       'Electrical Engineering', 'Mechanical Engineering',
       'Civil Engineering', 'Instrumentation Engineering'], dtype=object)

In [10]:
feed_data_test = feed_data.copy()
feed_data_test['avg_feedback'] = (feed_data_test.iloc[:,3]+feed_data_test.iloc[:,4]+feed_data_test.iloc[:,5]+feed_data_test.iloc[:,6]+feed_data_test.iloc[:,7]+feed_data_test.iloc[:,8]+feed_data_test.iloc[:,9]+feed_data_test.iloc[:,10]+feed_data_test.iloc[:,11]+feed_data_test.iloc[:,12]+feed_data_test.iloc[:,13]+feed_data_test.iloc[:,14]+feed_data_test.iloc[:,15]+feed_data_test.iloc[:,16]+feed_data_test.iloc[:,17])/15

In [11]:
feed_data_test.avg_feedback

0        5.400000
1        5.133333
2        4.066667
3        4.600000
4        5.266667
           ...
14395    5.266667
14396    5.533333
14397    4.666667
14398    5.000000
14399    4.333333
Name: avg_feedback, Length: 14400, dtype: float64

In [12]:
feed_data_test.head(2)

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
0,Computer Science and Engineering,1,1,7,4,8,9,2,7,7,2,8,7,6,3,8,2,1,5.400000
1,Computer Science and Engineering,1,1,2,1,7,10,10,3,3,9,5,6,1,5,7,4,4,5.133333

In [13]:
tot_feed_data = feed_data_test.groupby(['dept'])

In [14]:
cse_dept_feed = tot_feed_data.get_group('Computer Science and Engineering')
print(cse_dept_feed.dept.value_counts())
cse_dept_feed.head(3)

Computer Science and Engineering    2240
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
0,Computer Science and Engineering,1,1,7,4,8,9,2,7,7,2,8,7,6,3,8,2,1,5.400000
1,Computer Science and Engineering,1,1,2,1,7,10,10,3,3,9,5,6,1,5,7,4,4,5.133333
2,Computer Science and Engineering,1,1,1,3,2,5,8,7,1,7,5,5,3,4,0,8,2,4.066667

In [15]:
it_dept_feed = tot_feed_data.get_group('Information Technology')
print(it_dept_feed.dept.value_counts())
it_dept_feed.head(3)

Information Technology    2240
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
2240,Information Technology,1,1,4,10,1,10,1,6,8,5,10,5,3,4,2,5,0,4.933333
2241,Information Technology,1,1,6,7,9,1,1,2,10,0,0,6,7,2,6,4,5,4.400000
2242,Information Technology,1,1,5,5,3,4,9,2,9,6,9,2,2,1,3,4,7,4.733333

In [16]:
ce_dept_feed = tot_feed_data.get_group('Civil Engineering')
print(ce_dept_feed.dept.value_counts())
ce_dept_feed.head(3)

Civil Engineering    2240
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
11200,Civil Engineering,1,1,4,6,8,7,6,4,3,3,9,8,3,8,7,0,6,5.466667
11201,Civil Engineering,1,1,3,8,2,2,9,4,5,10,2,3,1,3,6,10,7,5.000000
11202,Civil Engineering,1,1,9,2,6,8,8,8,9,6,0,3,3,2,2,5,9,5.333333

In [17]:
ee_dept_feed = tot_feed_data.get_group('Electrical Engineering')
print(ee_dept_feed.dept.value_counts())
ee_dept_feed.head(3)

Electrical Engineering    2240
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
6720,Electrical Engineering,1,1,5,9,10,2,9,7,5,8,1,6,8,8,3,0,8,5.933333
6721,Electrical Engineering,1,1,8,9,4,8,2,1,1,3,9,1,3,0,1,8,2,4.000000
6722,Electrical Engineering,1,1,7,9,7,1,2,2,0,8,0,9,6,6,5,9,8,5.266667

In [18]:
me_dept_feed = tot_feed_data.get_group('Mechanical Engineering')
print(me_dept_feed.dept.value_counts())
me_dept_feed.head(3)

Mechanical Engineering    2240
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
8960,Mechanical Engineering,1,1,3,5,4,7,6,3,4,1,1,1,6,2,0,9,1,3.533333
8961,Mechanical Engineering,1,1,9,1,5,6,5,5,7,8,1,2,0,1,4,0,3,3.800000
8962,Mechanical Engineering,1,1,2,10,9,5,2,8,5,2,7,0,6,1,1,3,8,4.600000

In [19]:
extc_dept_feed = tot_feed_data.get_group('Electronic and Telecommunication Engineering')
print(extc_dept_feed.dept.value_counts())
extc_dept_feed.head(3)

Electronic and Telecommunication Engineering    2240
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
4480,Electronic and Telecommunication Engineering,1,1,8,9,5,10,2,6,5,3,9,2,3,7,5,9,4,5.800000
4481,Electronic and Telecommunication Engineering,1,1,3,7,1,8,8,8,5,2,3,7,3,1,9,9,10,5.600000
4482,Electronic and Telecommunication Engineering,1,1,9,5,5,10,3,5,9,8,1,1,4,3,1,7,3,4.933333

In [20]:
ins_dept_feed = tot_feed_data.get_group('Instrumentation Engineering')
print(ins_dept_feed.dept.value_counts())
ins_dept_feed.head(3)

Instrumentation Engineering    960
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
13440,Instrumentation Engineering,1,1,10,10,1,3,2,8,9,2,2,0,8,8,3,7,7,5.333333
13441,Instrumentation Engineering,1,1,4,8,2,1,7,1,7,7,7,2,9,5,6,3,5,4.933333
13442,Instrumentation Engineering,1,1,6,6,6,3,0,10,5,6,4,4,6,3,2,7,3,4.733333

In [21]:
tot_clg_feed = feed_data_test.copy()
print(tot_clg_feed.dept.value_counts())
tot_clg_feed.head(3)

Computer Science and Engineering                2240
Information Technology                          2240
Electronic and Telecommunication Engineering    2240
Electrical Engineering                          2240
Mechanical Engineering                          2240
Civil Engineering                               2240
Instrumentation Engineering                      960
Name: dept, dtype: int64

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
0,Computer Science and Engineering,1,1,7,4,8,9,2,7,7,2,8,7,6,3,8,2,1,5.400000
1,Computer Science and Engineering,1,1,2,1,7,10,10,3,3,9,5,6,1,5,7,4,4,5.133333
2,Computer Science and Engineering,1,1,1,3,2,5,8,7,1,7,5,5,3,4,0,8,2,4.066667

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
tot_clg_feed['dept'] = LabelEncoder().fit_transform(tot_clg_feed['dept'])
tot_clg_feed.head(3)

,dept,year,course,course_material,blackboard_systematic,audio_visual_used,lectures_with_examples,difficult_topics,faculty_command_subject,teacher_enthusiastic,communication_skills,lectures_interactive,improve_concepts,teacher_effective_preparation,level_of_ass_test,evaluation_fair,additional_info,teacher_accessible,avg_feedback
0,1,1,1,7,4,8,9,2,7,7,2,8,7,6,3,8,2,1,5.400000
1,1,1,1,2,1,7,10,10,3,3,9,5,6,1,5,7,4,4,5.133333
2,1,1,1,1,3,2,5,8,7,1,7,5,5,3,4,0,8,2,4.066667

In [24]:
tot_clg_feed.dept.value_counts()

1    2240
4    2240
3    2240
2    2240
6    2240
0    2240
5     960
Name: dept, dtype: int64

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
scaler = MinMaxScaler()

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_tot = tot_clg_feed.iloc[:,3:18]

In [29]:
y_tot = tot_clg_feed.iloc[:,18]

In [30]:
print(X_tot.shape)
X_tot.values

(14400, 15)

array([[7, 4, 8, ..., 8, 2, 1],
       [2, 1, 7, ..., 7, 4, 4],
       [1, 3, 2, ..., 0, 8, 2],
       ...,
       [2, 3, 4, ..., 8, 6, 4],
       [7, 2, 5, ..., 3, 9, 8],
       [4, 3, 7, ..., 1, 1, 0]])

In [31]:
y_tot_reshaped = np.array(y_tot).reshape(-1,1)
print(y_tot_reshaped.shape)
y_tot_reshaped

(14400, 1)

array([[5.4       ],
       [5.13333333],
       [4.06666667],
       ...,
       [4.66666667],
       [5.        ],
       [4.33333333]])

In [32]:
scaled_X_tot = scaler.fit_transform(X_tot)

In [33]:
print(scaled_X_tot.shape)
scaled_X_tot

(14400, 15)

array([[0.7, 0.4, 0.8, ..., 0.8, 0.2, 0.1],
       [0.2, 0.1, 0.7, ..., 0.7, 0.4, 0.4],
       [0.1, 0.3, 0.2, ..., 0. , 0.8, 0.2],
       ...,
       [0.2, 0.3, 0.4, ..., 0.8, 0.6, 0.4],
       [0.7, 0.2, 0.5, ..., 0.3, 0.9, 0.8],
       [0.4, 0.3, 0.7, ..., 0.1, 0.1, 0. ]])

In [34]:
X_tot_train,X_tot_test,y_tot_train,y_tot_test = train_test_split(scaled_X_tot,y_tot_reshaped,test_size=0.33,random_state=42)

In [35]:
print(X_tot_train.shape)
print(X_tot_test.shape)
X_tot_train

(9648, 15)
(4752, 15)

array([[0.2, 0. , 0.8, ..., 0.1, 0.2, 0.9],
       [0.9, 0.9, 0.5, ..., 0.2, 0.5, 0.7],
       [0.3, 1. , 0.7, ..., 0.2, 0.6, 0.7],
       ...,
       [0.1, 0.1, 0.8, ..., 0.8, 0.8, 0.1],
       [0.2, 0.7, 0.8, ..., 0.4, 1. , 0.1],
       [0.2, 1. , 0.6, ..., 0.8, 0.2, 0.9]])

In [36]:
print(y_tot_train.shape)
print(y_tot_test.shape)

(9648, 1)
(4752, 1)

In [37]:
#import tensorflow as tf
#from tensorflow import keras

In [38]:
# tot_dept_model = keras.Sequential([
#     keras.layers.Dense(10,input_shape = (15,),activation="relu"),
#     keras.layers.Dense(6,activation="relu"),
#     keras.layers.Dense(3,activation="relu"),
#     keras.layers.Dense(1,activation="sigmoid")
# ])

# tot_dept_model.compile(
#     optimizer="adam",
#     loss = "mean_absolute_error",
#     metrics=['accuracy'],
# )

# tot_dept_model.fit(X_tot_train,y_tot_train,epochs=5)

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
all_dept_model = LinearRegression().fit(X_tot_train,y_tot_train)

In [41]:
all_dept_model.score(X_tot_test,y_tot_test)

1.0

In [42]:
y_tot_pred = all_dept_model.predict(X_tot_test)
y_tot_pred.shape

(4752, 1)

In [43]:
y_tot_test.shape

(4752, 1)

In [44]:
y_tot_pred

array([[5.4       ],
       [4.46666667],
       [5.13333333],
       ...,
       [4.86666667],
       [6.26666667],
       [4.73333333]])